### PR TITLE
Added the ability to click and drag a tile

### PR DESCRIPTION
**Pull request by TuckerBMorgan**
Hey 
Like your tool, just added the ability to click and drag a new tile onto the board. 
Tucker Morgan

### CODE REVIEW

**Comment by victorqribeiro** [comment]
did you tested it on mobile? pretty sure you code would work with touchmove also, but I'm on a phone, can really test right now

**Comment by TuckerBMorgan** [comment]
Sorry I did not test it on Mobile, seems like it worked?

**Comment by victorqribeiro** [comment]
I merged, cause I can't really look at it right now, but tomorrow I'll fix everything not working properly. you can, if you want, to take a look at it and making another pull request

**Comment by victorqribeiro** [comment]
@all-contributors please add @TuckerBMorgan for Usability

**Pull request merged**
