### PR TITLE
allow right click to clear a tile

### PR DESCRIPTION
**Pull request by simonsarris**
For this I had to switch from 'click' to 'mouseup', also perhaps controversially, remove the context menu. I tried to stick to your minimalistic coding style.

This edit also trimmed trailing whitespace.

### CODE REVIEW

**Comment by victorqribeiro** [comment]
I'm afraid I can't accept this as it would break touch events. any suggestions?

**Comment by victorqribeiro** [comment]
maybe just add a mousedown event without removing the click one, cause click also is triggered by touch on touch devices

**Comment by simonsarris** [comment]
A slightly different way to consider is to add `touchend` and `pointerup` (ie touch devices like surface).

This is a little more future proof than using "click" because ultimately you may want to control the whole down-move-up process of clicks and touches (like for dragging across and making many buildings with one go)

**Comment by victorqribeiro** [comment]
@all-contributors please add @simonsarris for Usability

**Pull request merged**
